# Generated by Django 4.2.7 on 2023-12-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
