# Generated by Django 4.2.7 on 2025-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_task_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance & Repairs'), ('safety', 'Safety & Compliance'), ('crew', 'Crew Management'), ('cargo', 'Cargo & Logistics')], default='general', max_length=50),
        ),
    ]
