# Generated by Django 4.2.7 on 2025-02-18 20:20

import authsystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=authsystem.models.default_deadline),
        ),
    ]
